logbook:
  exclude:
    entity_globs:
      - sensor.*_last_seen

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

script: !include scripts.yaml
automation: !include automations.yaml

media_source:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.16.0.0/16
    - 192.168.0.0/24

# Make sure Pyscript is installed via HACS!
pyscript: !include pyscript/config.yaml
