services:
  RouterRebooter:
    image: mwdle/router_rebooter:latest
    container_name: RouterRebooter
    restart: unless-stopped
    hostname: routerrebooter
    networks:
      - RouterRebooter
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_VOLUMES}/HomeAssistant/.ssh/id_rsa.pub:/root/.ssh/authorized_keys:ro
      - ${DOCKER_VOLUMES}/RouterRebooter/secrets/router_pass:/RouterRebooter/secrets/router_pass:ro
      - ${DOCKER_VOLUMES}/RouterRebooter/secrets/extender_pass:/RouterRebooter/secrets/extender_pass:ro
      - ${DOCKER_VOLUMES}/RouterRebooter/data:/RouterRebooter/data
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080
      - SCREEN_DEPTH=24
      - TZ=America/Denver
    deploy:
      resources:
        limits: 
          cpus: '0.50'
          memory: 250M

  MQTT:
    image: eclipse-mosquitto
    container_name: MQTT
    restart: unless-stopped
    hostname: mqtt
    networks:
      - HomeAssistant
      - Frigate
    volumes:
      - ${DOCKER_VOLUMES}/MQTT/log:/mosquitto/log
      - ${DOCKER_VOLUMES}/MQTT/data:/mosquitto/data
      - ${DOCKER_VOLUMES}/MQTT/config:/mosquitto/config

  Frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: Frigate
    restart: unless-stopped
    privileged: true # Must be privileged to enable hardward acceleration. This allows access intel_gpu_top command for gpu stats .
    shm_size: "64mb" # update for your cameras based on calculation from installation guide
    devices:
      - /dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    ports:
      - 8555:8555 # WebRTC
    hostname: frigate
    networks:
      - Frigate
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_VOLUMES}/Frigate/config:/config
      - ${DOCKER_VOLUMES}/Frigate/storage:/media/frigate
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    environment:
      FRIGATE_RTSP_USER: "${RTSP_USER}"
      FRIGATE_RTSP_PASSWORD: "${RTSP_PASSWORD}"
      FRIGATE_MQTT_USER: "${MQTT_USER}"
      FRIGATE_MQTT_PASSWORD: "${MQTT_PASSWORD}"
    depends_on:
      - MQTT

  MusicAssistant:
    container_name: MusicAssistant
    image: ghcr.io/music-assistant/server:latest
    restart: unless-stopped
    hostname: musicassistant
    networks:
      AAA_LAN:
      MusicAssistant:
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKER_VOLUMES}/MusicAssistant/data:/data
      - ${MUSIC_VOLUME}:/media
  
  HomeAssistant:
    image: ghcr.io/home-assistant/home-assistant:latest
    container_name: HomeAssistant
    restart: unless-stopped
    hostname: homeassistant
    networks:
      AAA_LAN:
      HomeAssistant:
      RouterRebooter:
    volumes:
      - ${DOCKER_VOLUMES}/HomeAssistant/config:/config
      - ${DOCKER_VOLUMES}/HomeAssistant/.ssh:/root/.ssh
      - /etc/localtime:/etc/localtime:ro
    environment:
      ROUTER_PASSWORD: ${ROUTER_PASSWORD}
      EXTENDER_PASSWORD: ${EXTENDER_PASSWORD}
    depends_on:
      - RouterRebooter
      - MQTT
      - Frigate
      - MusicAssistant

networks:
  AAA_LAN:
    name: AAA_LAN
    external: true
  HomeAssistant:
    name: HomeAssistant
    external: true
  RouterRebooter:
    name: RouterRebooter
    external: true
  Frigate:
    name: Frigate
    external: true
  MusicAssistant:
    name: MusicAssistant
    external: true